name: Update jsp daily-note blog.
on:
  repository_dispatch:
    types: [obsidian-updated]

jobs:
  update-blog-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   submodules: recursive
        #   token: ${{ secrets.JSP_DAILYNOTE_BLOG_TOKEN }}

      # - name: Update blog contents.
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@user.noreply.github.com'

      #     git submodule update --remote --recursive
      #     git add .

      #     if [ -z "$(git status --porcelain)" ]; then
      #       echo "No changes detected in submodule."
      #       exit 0
      #     fi

      #     git commit -m "👊 Update jsp daily-note blog content submodule"
      #     git push

      - name: Clond /blog/publish from note repo
        env:
          TOKEN: ${{ secrets.JSP_DAILYNOTE_BLOG_TOKEN }}
          URL: ${{ vars.JSP_DAILYNOTE_URL }}
        run: |
          git clone --depth=1 --filter=blob:none --sparse https://x-accecss-token:${TOKEN}@${URL}.git publish-note
          cd publish-note
          git sparse-checkout init --cone
          git sparse-checkout set blog/publish/
          rsync -av blog/publish/ ../content/

      - name: Set up Node.js to 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install deps
        run: npm i

      - name: Build
        run: npx quartz build
