name: Update jsp daily-note blog.
on:
  repository_dispatch:
    types: [obsidian-updated]

jobs:
  update-blog-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.JSP_DAILYNOTE_SSH_KEY }}

      - name: Setup Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Update blog contents
        run: |
          echo "✅ Submodule Updating..."
          git submodule update --remote --recursive

          git add .

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
          else
            git commit -m "🔁 Add or update submodule"
            git push origin HEAD
          fi

      - name: Set up Node.js to 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm i

      - name: Build and push Contents.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx quartz build
